### ISSUE TITLE
我记得这个字应该是念    Xi  吧

### ISSUE THREAD

**Issue by FlowerBoot** [Alimei/hangzhouYunQi2017ppt#1]
本人有点小小的强迫症........../哭笑

**Comment by wjzhu-class** [comment]
栖息:qi xi
读Xi 的时候很少的，此处按意思来看，念qi 没问题。

FYI：
栖
qī
鸟禽歇宿：“夫以鸟养养鸟者，宜栖之深林”。
居留，停留：栖身。栖息。栖止。栖遁（隐居，遁世）。栖迟（游息，居住）。
栖
xī
〔栖栖〕形容不安定。
〔栖遑〕ａ．忙碌不安，到处奔波；ｂ．被迫。均亦作“栖皇”。

**Comment by coolyaolei** [comment]
老铁~没毛病~

**Comment by Winly-40** [comment]
老铁没毛病

**Comment by lilyjazz** [comment]
阔以，没毛病

**Comment by telenewbie** [comment]
厉害了.

**Comment by LuXIN** [comment]
老铁d=====(￣▽￣*)b厉害
